<a href="https://colab.research.google.com/github/Tech-Dheer/NNDL-Lab/blob/colab-branch/XOR_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

In [ ]:
w11 = np.asarray([1,1])
w12 = np.asarray([1,1])
w2 = np.asarray([-1,1])

B1 = np.asarray([-1.5,-0.5])
B2 = np.asarray([-0.5])

In [ ]:
w11

array([1, 1])

In [ ]:
w12

array([1, 1])

In [ ]:
B1

array([-1.5, -0.5])

In [ ]:
B2

array([-0.5])

In [ ]:
x = X[0]
print(x)

[0 0]


In [ ]:
len(w11)

2

In [ ]:
def summation(x,Wt1,Wt2,Bs):
  sumh=[0,0]
  for i in range(len(x)):
    sumh[i]=(x[0]*Wt1[i]+x[1]*Wt2[i])+Bs[i]
  return sumh

In [ ]:
sumv = summation(x,w11,w12,B1)
print(sumv)

[-1.5, -0.5]


In [ ]:
def Heaviside (net):
  if net >= 0:
    return 1
  else:
    return 0

In [ ]:
hidden = [0,0]
for i in range(len(sumv)):
  hidden[i] = Heaviside(sumv[i])

In [ ]:
print(hidden)

[0, 0]


In [ ]:
sumo = np.dot(hidden,w2) + B2[0]
y_pred = Heaviside(sumo)

In [ ]:
print(y_pred)

0


In [ ]:
y_pred=[]
for i in range(X.shape[0]):
  x=X[i]
  sumv=summation(x,w11,w12,B1)
  hidden=[0,0]
  for i in range(len(sumv)):
    hidden[i]=Heaviside(sumv[i])
  sumo=np.dot(hidden,w2)+B2[0]
  y_pred.append(Heaviside(sumo))

In [ ]:
y_pred

[0, 1, 1, 0]